In [7]:
!pip install numpy



[notice] A new release of pip is available: 24.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy as np

# create array using np

arr1=np.array([1,3,4,5,6])
print(arr1)
print(type(arr1))
print(arr1.shape)


[1 3 4 5 6]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,3,4,5,6])
arr2.reshape((1,5)) # 1 row and 5 coloumn

array([[1, 3, 4, 5, 6]])

In [12]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr2.shape)
print(arr2)

(2, 5)
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of array
arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:\n",arr.shape)
print("Number of dimensions:\n",arr.ndim)
print("Size(number of elements):\n",arr.size)
print("Data type:\n",arr.dtype)
print("Item size (in bytes):\n",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of dimensions:
 2
Size(number of elements):
 6
Data type:
 int64
Item size (in bytes):
 8


In [23]:
#Numpy Vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print("Addition:",arr1+arr2)
print("Substraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Division:",arr1/arr2)

Addition: [ 7  9 11 13 15]
Substraction: [-5 -5 -5 -5 -5]
Multiplication: [ 6 14 24 36 50]
Division: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [ ]:
#universal function
arr1=np.array([1,2,3,4,5])
#squrae root
print(np.sqrt(arr1))
#exponential
print(np.exp(arr1))
#sin
print(np.sin(arr1))
#log
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [10]:
#array slicing and indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,3],[3,5,2,5,3]])
print(arr)



[[1 2 3 4 5]
 [6 7 8 9 3]
 [3 5 2 5 3]]


In [15]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4 5]
 [8 9 3]]


In [12]:
arr[1:,2:]

array([[8, 9, 3],
       [2, 5, 3]])

In [17]:
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9   3]
 [  3   5   2   5   3]]


In [18]:
arr[1:]=100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [21]:
data=np.array([1,2,3,4,5])
mean=np.mean(data)
print(mean)

median=np.median(data)
print(median)

std_dev=np.std(data)
print(std_dev)

variance=np.var(data)
print(variance)


3.0
3.0
1.4142135623730951
2.0


In [27]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])